<a href="https://colab.research.google.com/github/flauflauf/llm-hackathon/blob/main/LLM_Hackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tiktoken openai torch transformers accelerate bitsandbytes optimum auto-gptq

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 27.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 217.9/217.9 kB 19.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 109.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.4/261.4 kB 34.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 MB 9.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 398.9/398.9 kB 45.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 104.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 kB 10.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 38.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 94.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 62.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━

# Open Source LLMs nutzen

In [ ]:
!huggingface-cli login --token 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

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [ ]:
from transformers import AutoModelForCausalLM,AutoTokenizer
import torch

In [ ]:
mn = "meta-llama/Llama-2-7b-hf"

In [ ]:
tokr = AutoTokenizer.from_pretrained(mn)
prompt = "Jeremy Howard is a "
toks = tokr(prompt, return_tensors="pt")

In [ ]:
toks

{'input_ids': tensor([[    1,  5677,  6764, 17430,   338,   263, 29871]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
tokr.batch_decode(toks['input_ids'])

['<s> Jeremy Howard is a ']

In [ ]:
model = AutoModelForCausalLM.from_pretrained(mn, device_map=0, load_in_8bit=True)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
%%time
res = model.generate(**toks.to("cuda"), max_new_tokens=15).to('cpu')
res

CPU times: user 1.2 s, sys: 91.8 ms, total: 1.29 s
Wall time: 1.3 s


tensor([[    1,  5677,  6764, 17430,   338,   263, 29871, 29906, 29947,  1629,
          2030, 23440,  1600,   332,   322,  6601,  9638,   391, 29889,   940,
           338,   278]])

In [ ]:
tokr.batch_decode(res)

['<s> Jeremy Howard is a 28 year old entrepreneur and computer scientist. He is the']

In [ ]:
# Clear memory

from numba import cuda
device = cuda.get_current_device()
device.reset()

In [ ]:
model = AutoModelForCausalLM.from_pretrained(mn, device_map=0, torch_dtype=torch.bfloat16)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
%%time
res = model.generate(**toks.to("cuda"), max_new_tokens=15).to('cpu')
res

CPU times: user 1.07 s, sys: 20.3 ms, total: 1.09 s
Wall time: 2.09 s


tensor([[    1,  5677,  6764, 17430,   338,   263, 29871, 29906, 29900, 29896,
         29945,  4326,  1433,  9743, 25940,   322,   278, 14645, 29949,   310,
          1174, 19411]])

In [ ]:
tokr.batch_decode(res)

['<s> Jeremy Howard is a 35-year-old man from the United States who was arrested in']

In [ ]:
# Clear memory

from numba import cuda
device = cuda.get_current_device()
device.reset()

In [ ]:
model = AutoModelForCausalLM.from_pretrained('TheBloke/Llama-2-7b-Chat-GPTQ', device_map=0, torch_dtype=torch.float16)

In [ ]:
%%time
res = model.generate(**toks.to("cuda"), max_new_tokens=15).to('cpu')
res

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1421: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use and modify the model generation configuration (see https://huggingface.co/docs/transformers/generation_strategies#default-text-generation-configuration )
  warnings.warn(


CPU times: user 1.74 s, sys: 266 ms, total: 2.01 s
Wall time: 4.96 s


tensor([[    1,  5677,  6764, 17430,   338,   263, 29871, 29941, 29945, 29899,
          6360, 29899,  1025,   767,   515,   278,  3303,  3900,  1058,   471,
         24383,   297]])

In [ ]:
mn = 'TheBloke/Llama-2-13B-GPTQ'
model = AutoModelForCausalLM.from_pretrained(mn, device_map=0, torch_dtype=torch.float16)

In [ ]:
%%time
res = model.generate(**toks.to("cuda"), max_new_tokens=15).to('cpu')
res

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1421: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use and modify the model generation configuration (see https://huggingface.co/docs/transformers/generation_strategies#default-text-generation-configuration )
  warnings.warn(


CPU times: user 1.4 s, sys: 81.8 ms, total: 1.48 s
Wall time: 1.56 s


tensor([[    1,  5677,  6764, 17430,   338,   263, 29871, 29906, 29900, 29896,
         29947, 29899, 29906, 29900, 29896, 29929, 23004,  1182,   523,  1102,
         10170,   322]])

In [ ]:
def gen(p, maxlen=15, sample=True):
    toks = tokr(p, return_tensors="pt")
    res = model.generate(**toks.to("cuda"), max_new_tokens=maxlen, do_sample=sample).to('cpu')
    return tokr.batch_decode(res)

In [ ]:
%%time
gen(prompt, 100)

CPU times: user 6.69 s, sys: 65.9 ms, total: 6.75 s
Wall time: 6.84 s


['<s> Jeremy Howard is a 3x serial entrepreneur (1x from scratch, 2x as co-founder). He has worked extensively in both enterprise and consumer applications of machine learning (founder of Kaggle, the largest data science platform with millions of competitions, over 18 million members and now owned by Google) in fields including image recognition, speech recognition, language understanding, and fraud detection. He is currently Co-Founder & President of the global public health company ME']

# Fine tuning

## Datensatz

In [ ]:
import datasets

[knowrohit07/know_sql](https://huggingface.co/datasets/knowrohit07/know_sql)

In [ ]:
ds = datasets.load_dataset('knowrohit07/know_sql', revision='f33425d13f9e8aab1b46fa945326e9356d6d5726')

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
ds

DatasetDict({
    train: Dataset({
        features: ['question', 'answer', 'context'],
        num_rows: 78562
    })
})

In [ ]:
trn = ds['train']
trn[3]

{'question': 'What are the hosts of competitions whose theme is not "Aliens"?',
 'answer': "SELECT Hosts FROM farm_competition WHERE Theme <> 'Aliens'",
 'context': 'CREATE TABLE farm_competition (Hosts VARCHAR, Theme VARCHAR)'}

## Axolotl

In [ ]:
!git clone https://github.com/OpenAccess-AI-Collective/axolotl
%cd axolotl

Cloning into 'axolotl'...
remote: Enumerating objects: 7612, done.
remote: Counting objects: 100% (1419/1419), done.
remote: Compressing objects: 100% (276/276), done.
remote: Total 7612 (delta 1288), reused 1162 (delta 1136), pack-reused 6193
Receiving objects: 100% (7612/7612), 2.63 MiB | 5.12 MiB/s, done.
Resolving deltas: 100% (4899/4899), done.
/content/axolotl


In [ ]:
!pip3 install packaging
!pip3 install -e '.[flash-attn,deepspeed]'
!pip3 install -U git+https://github.com/huggingface/peft.git

Obtaining file:///content/axolotl
  Preparing metadata (setup.py) ... done
  Cloning https://github.com/huggingface/peft.git to /tmp/pip-install-oy1n70h4/peft_09a68bb5c19a4d419c864197119ebdd6
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /tmp/pip-install-oy1n70h4/peft_09a68bb5c19a4d419c864197119ebdd6
  Resolved https://github.com/huggingface/peft.git to commit d9094cebea954760259295875b656846f9364d39
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Cloning https://github.com/huggingface/transformers.git (to revision acc394c4f5e1283c19783581790b3dc3105a3697) to /tmp/pip-install-oy1n70h4/transformers_2195bf77be3245268cdb8780f81b2465
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-install-oy1n70h4/transformers_2195bf77be3245268cdb8780f81b2465
  Running command git rev-parse -q --verify 'sha^

In [ ]:
# finetune lora
!accelerate launch -m axolotl.cli.train examples/openllama-3b/lora.yml

# inference
!accelerate launch -m axolotl.cli.inference examples/openllama-3b/lora.yml \
    --lora_model_dir="./lora-out"

In [ ]:
!accelerate launch -m axolotl.cli.train sql.yml

`accelerate launch -m axolotl.cli.train sql.yml`

In [ ]:
tst = dict(**trn[3])
tst['question'] = 'Get the count of competition hosts by theme.'
tst

{'answer': "SELECT Hosts FROM farm_competition WHERE Theme <> 'Aliens'",
 'context': 'CREATE TABLE farm_competition (Hosts VARCHAR, Theme VARCHAR)',
 'question': 'Get the count of competition hosts by theme.'}

In [ ]:
fmt = """SYSTEM: Use the following contextual information to concisely answer the question.

USER: {}
===
{}
ASSISTANT:"""

In [ ]:
def sql_prompt(d): return fmt.format(d["context"], d["question"])

In [ ]:
print(sql_prompt(tst))

SYSTEM: Use the following contextual information to concisely answer the question.

USER: CREATE TABLE farm_competition (Hosts VARCHAR, Theme VARCHAR)
===
List all competition hosts sorted in ascending order.
ASSISTANT:


In [ ]:
import torch
from peft import PeftModel
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

In [ ]:
ax_model = '/home/jhoward/git/ext/axolotl/qlora-out'

In [ ]:
tokr = AutoTokenizer.from_pretrained('meta-llama/Llama-2-7b-hf')

In [ ]:
model = AutoModelForCausalLM.from_pretrained('meta-llama/Llama-2-7b-hf',
                                             torch_dtype=torch.bfloat16, device_map=0)
model = PeftModel.from_pretrained(model, ax_model)
model = model.merge_and_unload()
model.save_pretrained('sql-model')

In [ ]:
toks = tokr(sql_prompt(tst), return_tensors="pt")

In [ ]:
res = model.generate(**toks.to("cuda"), max_new_tokens=250).to('cpu')

In [ ]:
print(tokr.batch_decode(res)[0])

<s> SYSTEM: Use the following contextual information to concisely answer the question.

USER: CREATE TABLE farm_competition (Hosts VARCHAR, Theme VARCHAR)
===
Get the count of competition hosts by theme.
ASSISTANT: SELECT COUNT(Hosts), Theme FROM farm_competition GROUP BY Theme</s>
